### ISSUE TITLE
Request code for non-global gather operation

### ISSUE THREAD

**Issue by SaoYan** [hujie-frank/GENet#8]
Hi there,

It seems that you only release the code with global gathering.

Parameter free: all gather layers use global-average-pooling, e.g. [this line](https://github.com/hujie-frank/GENet/blob/master/models/RN50-GEPF.prototxt#L272).

Parameter (depth-wise-conv): you are using kernel-size that is the same as feature spatial size, e.g. [this line](https://github.com/hujie-frank/GENet/blob/master/models/RN50-GEP.prototxt#L273)

Could you release the code for local-wise gathering? (e.g. downsample with a factor of 8/4/2 and then interpolate during exciting) @hujie-frank

**Comment by kayuksel** [comment]
@SaoYan There is an unofficial implementation, on which I have also done some code structuring here:

https://github.com/kayuksel/pytorch-GENet/blob/master/models/blocks.py

I am unsure if the unofficial implementation perfectly matches the method in the paper, since that I have not tested it. But it includes an extent parameter which should be controlling the local-wise gathering.

Please, feel more than welcome to contribute to this implementation if you are also working with PyTorch.

**Comment by SaoYan** [comment]
thans, I'll check~
